// examples/angular-dapp/src/app/source-code/source-code.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-source-code',
  templateUrl: './source-code.component.html',
  styleUrls: ['./source-code.component.css']
})
export class SourceCodeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="source-code">
  <p>Source code:</p>
  <a href="https://github.com/energywebfoundation/iam-client-lib/tree/develop/examples/angular-dapp">
    <img src="../../assets/GitHub-Mark-32px.png"/>
  </a>
</div>

// examples/react-dapp/src/components/SourceCode.tsx
import React from 'react'
import './SourceCode.css'
import githubLogo from '../assets/GitHub-Mark-32px.png'

function SourceCode() {
    return (
      <div className="source-code">
        <p>Source code:</p>
        <a href="https://github.com/energywebfoundation/iam-client-lib/tree/develop/examples/react-dapp">
          <img src={githubLogo}/>
        </a>
      </div>
    )
}

export default SourceCode
