// examples/angular-dapp/src/app/app.component.ts
import { Component } from '@angular/core';
import axios from 'axios'
import { IamService } from './iam.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(
    private readonly iamService: IamService
  ) { }

  isLoading: boolean = false
  did = undefined
  roles: Role[]

  async verifyIdentity() {
    const claim = await this.iamService.iam.createIdentityProof();
    const {
      data: { token }
    } = await axios.post<{ token: string }>("https://did-auth-demo.energyweb.org/login", {
      claim
    });
    const config = {
      headers: { Authorization: `Bearer ${token}` }
    };
    const { data: roles } = await axios.get<Role[]>(
      "https://did-auth-demo.energyweb.org/roles",
      config
    );
    this.roles = roles;
  }

  async login({ useMetamaskExtension }: { useMetamaskExtension: boolean }) {
    this.isLoading = true;
    const { did } = await this.iamService.iam.initializeConnection({ useMetamaskExtension });
    if (did) {
      this.did = did;
      try {
        await this.verifyIdentity();
      } catch (err) {
        this.isLoading = false;
      }
    }
    this.isLoading = false;
  }

  logout() {
    this.did = "";
  }
}

type Role = {
  name: string;
  namespace: string;
};
<div>
  <div id="app">
    <img alt="Vue logo" src="./assets/angular.png" />
    <h2>IAM showcase app</h2>
    <app-login></app-login>
    <app-source-code></app-source-code>
  </div>
</div>

// examples/react-dapp/src/App.tsx
import React, { useState } from 'react'
import './App.css'
import './Login.css'
import { IAM, CacheServerClient } from 'iam-client-lib'
import axios from 'axios'
import logo from './assets/logo.svg'
import metamaskLogo from './assets/metamask-logo.svg'
import walletconnectIcon from './assets/wallet-connect-icon.svg'
import Spinner from './components/Spinner'

const cacheClient = new CacheServerClient({ url: 'https://volta-iam-cacheserver.energyweb.org/' })

const iam = new IAM({
  rpcUrl: 'https://volta-rpc.energyweb.org',
  chainId: 73799,
  cacheClient,
})

type Role = {
  name: string
  namespace: string
}

function App() {
  const [roles, setRoles] = useState<Role[]>([])
  const [did, setDID] = useState<string>('')
  const [isLoading, setIsLoading] = useState<Boolean>(false)

  const verifyIdentity = async function () {
    const claim = await iam.createIdentityProof();
    const { data } = await axios.post<{ token: string }>(
      "https://did-auth-demo.energyweb.org/login",
      {
        claim
      }
    );
    const config = {
      headers: { Authorization: `Bearer ${data.token}` }
    };
    const { data: roles } = await axios.get<Role[]>(
      "https://did-auth-demo.energyweb.org/roles",
      config
    );
    setRoles(roles);
  }

  const login = async function (initOptions?: {
    useMetamaskExtension: boolean;
  }) {
    setIsLoading(true);
    const { did } = await iam.initializeConnection(initOptions);
    if (did) {
      setDID(did)
      try {
        await verifyIdentity();
      } catch (err) {
        console.error(err)
      }
    }
    setIsLoading(false);
  }

  const loginWithWalletConnect = async function () {
    setIsLoading(true);
    const { did } = await iam.initializeConnection();
    if (did) {
      setDID(did)
      try {
        await verifyIdentity();
      } catch (err) {
        console.error(err)
      }
    }
    setIsLoading(false);
  }

  const logout = function () {
    setDID('');
  }

  const renderLoading = () => {
    return (
      <div>
        <Spinner />
        <span>
          Loading... (Please sign messages using your connected wallet)
        </span>
      </div>
    )
  }

  const renderLoginResults = () => {
    return (
      <div>
        <p>Hello user!</p>
        <p>
          Your decentralised identifier: <br />
          <strong>{did}</strong>
        </p>
        {roles && roles.length > 0 ? (
          <div className="rolesContainer">
            <p>These are your validated roles:</p>
            {roles.map(({ name, namespace }) => (
              <p key={namespace}><strong>{`${name}`}</strong>{` at ${namespace}`}</p>
            ))}
          </div>
        )
          : (
            <div>
              You do not have any issued role at the moment, please login into switchboard and search for
              apps, orgs to enrol.
            </div>
          )}
        <div className="logoutContainer">
          <button onClick={logout} className="button">
            <span>Logout</span>
          </button>
        </div >
      </div >
    )
  }

  const renderLoginOptions = () => {
    return (
      <div className="container">
        <button className="button" onClick={async () => await loginWithWalletConnect()}>
          <img alt="walletconnect logo" className="walletconnect" src={walletconnectIcon} />
          <span>Login with Wallet Connect</span>
        </button>
        <button className="button" onClick={async () => await login({ useMetamaskExtension: true })}>
          <img alt="metamask logo" className="metamask" src={metamaskLogo} />
          <span>Login with Metamask</span>
        </button>
      </div>
    )
  }

  const loginJsx = () => {
    if (isLoading) {
      return renderLoading()
    }
    else if (did) {
      return renderLoginResults();
    }
    else {
      return renderLoginOptions();
    }
  };

  return (
    <div className="App">
      <img src={logo} className="App-logo" alt="logo" />
      <h2>IAM showcase app</h2>
      { loginJsx() }
    </div >
  )
}

export default App
